# Generated by Django 3.2.5 on 2021-07-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20210705_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestselling',
            new_name='is_bestseller',
        ),
    ]
